models:
  pretrained:
    yolo11m: models/pretrained/yolo11m.pt
    yolo26n: models/pretrained/yolo26n.pt
  component_model:
    name: Component
    path: models/trained/Component/Component_best.pt
  defect_mapping:
    arduino_uno:
      name: DeepPCB
      path: models/trained/DeepPCB/DeepPCB.pt
    esp32_devkit:
      name: DsPCBSD+
      path: models/trained/DsPCBSD+/DsPCBSD+.pt
    stm32_blue_pill:
      name: HRIPCB
      path: models/trained/HRIPCB/HRIPCB.pt
    generic_pcb:
      name: TDD-PCB
      path: models/trained/TDD-PCB/PDD-PCB-best.pt
